### ISSUE TITLE
CORS_ADDITIONAL_HEADERS env variable required to start

### ISSUE THREAD

**Issue by gonzaloriestra** [privacycloud/serverous#3]
When I try to run the latest version of the server (1.1.1), it shows this error:

```
{ AssertionError [ERR_ASSERTION]: Invalid server options {
  "port": "3000",
  "routes": {
    "cors": {
      "additionalHeaders": [
        "" [1]
      ],
      "credentials": true,
      "origin": [
        "*"
      ]
    }
  }
}

[1] "0" is not allowed to be empty
    at Object.exports.apply (/home/app/api/node_modules/hapi/lib/config.js:22:10)
    at Object.internals.setup (/home/app/api/node_modules/hapi/lib/core.js:597:23)
    at new module.exports.internals.Core (/home/app/api/node_modules/hapi/lib/core.js:57:46)
    at new module.exports (/home/app/api/node_modules/hapi/lib/server.js:25:18)
    at __dirname (/home/app/api/src/index.ts:9:20)
    at Object.<anonymous> (/home/app/api/src/index.ts:28:3)
    at Module._compile (module.js:643:30)
    at Module.m._compile (/home/app/api/node_modules/ts-node/src/index.ts:430:23)
    at Module._extensions..js (module.js:654:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/home/app/api/node_modules/ts-node/src/index.ts:433:12)
  generatedMessage: false,
  name: 'AssertionError [ERR_ASSERTION]',
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '==' }
```

My `docker-compose.yml` is similar to the sample in `README.md`. If I add a `CORS_ADDITIONAL_HEADERS` variable with any value in the `environment` section, then it works.

**Comment by sergioalvz** [comment]
This is published in 1.1.2
